# Generated by Django 4.2 on 2024-03-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qurilish_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Site_Users',
        ),
    ]
